---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-storage
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-storage
  resources:
    requests:
      storage: 15Gi