---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: solr-disk-storage
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: solr-disk-storage
  resources:
    requests:
      storage: 5Gi