apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
        #   runAsUser: 1000
        # resources:
        #   requests:
        #     memory: 100Mi
        #     cpu: 100m
        #   limits:
        #     memory: 2500Mi
        #     cpu: 500m
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: shared-data-pvc 
      imagePullSecrets:
        - name: sitecore-docker-registry
      
